### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 103: character maps to <undefined>

### ISSUE THREAD

**Issue by duncte123** [skoolkid/skoolkit#118]
After installing skoolkit I get the following error when running `tap2sna.py -d game @tape.tzx`

```
Traceback (most recent call last):
  File "C:\Users\dunca\AppData\Local\Programs\Python\Python39\Scripts\tap2sna.py", line 24, in <module>
    tap2sna.main(sys.argv[1:])
  File "C:\Users\dunca\AppData\Local\Programs\Python\Python39\lib\site-packages\skoolkit\tap2sna.py", line 514, in main
    namespace, unknown_args = parser.parse_known_args(args)
  File "C:\Users\dunca\AppData\Local\Programs\Python\Python39\lib\argparse.py", line 1851, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Users\dunca\AppData\Local\Programs\Python\Python39\lib\argparse.py", line 1866, in _parse_known_args
    arg_strings = self._read_args_from_files(arg_strings)
  File "C:\Users\dunca\AppData\Local\Programs\Python\Python39\lib\argparse.py", line 2123, in _read_args_from_files
    for arg_line in args_file.read().splitlines():
  File "C:\Users\dunca\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 103: character maps to <undefined>
```

also a side note: I can't use cmd or powershell on windows since powershell does not allow the `@` and cmd just opens the file in an editor

**Comment by skoolkid** [comment]
Is *tape.tzx* actually a TZX file? If so, that's the problem. The file marked by `@` is supposed to contain command line arguments for `tap2sna.py`. An example is [hungry_horace.t2s](https://github.com/skoolkid/skoolkit/blob/master/examples/hungry_horace.t2s).

**Comment by duncte123** [comment]
ah it works like that, the documentation is not easy to browse

**Comment by bleuge** [comment]
Sorry if it's not correct to put this here, but I looked the closed issues before and read the error I got is similar

I got this error using the skool file from your Rom spectrum disassembly repo: 
(running with Python 3.10.6 in W10 x64)

It produces a partial asm file.
Could this be related to codepages? My W10 is in spanish, and I launch this from commandline.

C:\dev\0zx\tools\skoolkit\00games\rom\sources>C:\dev\0zx\tools\skoolkit\skool2asm.py rom.skool > rom.asm
Parsed rom.skool (0.52s)
Traceback (most recent call last):
  File "C:\dev\0zx\tools\skoolkit\skool2asm.py", line 24, in <module>
    skool2asm.main(sys.argv[1:])
  File "C:\dev\0zx\tools\skoolkit\skoolkit\skool2asm.py", line 143, in main
    run(namespace.skoolfile, namespace, config)
  File "C:\dev\0zx\tools\skoolkit\skoolkit\skool2asm.py", line 70, in run
    clock(options.quiet, 'Wrote ASM to stdout', asm_writer.write)
  File "C:\dev\0zx\tools\skoolkit\skoolkit\skool2asm.py", line 30, in clock
    result = operation(*args, **kwargs)
  File "C:\dev\0zx\tools\skoolkit\skoolkit\skoolasm.py", line 176, in write
    self.print_entry()
  File "C:\dev\0zx\tools\skoolkit\skoolkit\skoolasm.py", line 208, in print_entry
    self.print_instructions()
  File "C:\dev\0zx\tools\skoolkit\skoolkit\skoolasm.py", line 479, in print_instructions
    self.write_line(oline)
  File "C:\dev\0zx\tools\skoolkit\skoolkit\skoolasm.py", line 213, in write_line
    write_text('{0}{1}'.format(s, self.end))
  File "C:\dev\0zx\tools\skoolkit\skoolkit\__init__.py", line 60, in write_text
    sys.stdout.write(text)
  File "C:\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2191' in position 28: character maps to <undefined>

**Comment by skoolkid** [comment]
Try setting the `PYTHONUTF8` environment variable.

https://docs.python.org/3/using/windows.html#utf-8-mode

**Comment by bleuge** [comment]
Parsed rom.skool (0.50s)
Wrote ASM to stdout (0.58s)

Worked perfect, thanks :D
I want a printed copy of the ROM to take notes, etc, 
Started learning z80 and zx stuff 👍
